name: tappay
description: TapPay — Contactless Digital Wallet with NFC Payments
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  device_info_plus: ^9.1.0
  nfc_manager: ^3.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
