name: tappay
description: TapPay — Contactless Digital Wallet with NFC Payments
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  device_info_plus: ^9.1.0
  nfc_manager: ^3.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.2
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.2
  path: ^1.8.3
  crypto: ^3.0.3
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
